### ISSUE TITLE
A better diagram

### ISSUE THREAD

**Issue by nponeccop** [zizon/qsocks#1]
I drew a better diagram of how qsocks works. Is it correct? I can make a PR then.

```
           SOCKS5/TCP                custom transport/QUIC                 TCP
client <----------------> qsocks <---------------------------> sqserver <-------> target
```

Is there a single QUIC connection between `qsocks` and `sqserver`? How does the custom transport layer looks like? You need to associate TCP connectons with QUIC streams.

**Comment by zizon** [comment]
The data flow is correct.

There are a configuration parameter controls how many client tcp connections share a qsocks QUIC Stream(by multiplexing a same session).

The Protocol between qsocks and sqserver are a bit like SOCK5, which merely pass the address part to the sqserver side.
 
Actually, there is a better/simple way to do by dropping/moving SOCKS5 to the current custom transport part, which can clearing wire protocols and simplify client side transactions(by just forward what ever it receive to qsocks and qsocks transparently forward it via QUIC) 
 
                     TCP.                   SOCKS5 in QUIC                     TCP
    client <----------------> qsocks <---------------------------> sqserver <-------> target

**Comment by zizon** [comment]
Close as date flow had changed.

Now the client side simply run inside QUIC, the server side do the full SOCKS5 protocol(not exactly though, but from a SOCKS5 user end it is so).
